version: '3.3'
services:
  serving:
    image: tensorflow/serving:2.12.1
    ports:
      - '8510:8500' # Whatever you need for client
      - '8511:8501' # Whatever you need for client
    environment:
      - MODEL_NAME=tencent
    hostname: 'serving'
    volumes:
      - '/home/marvin/workspace/DeepRec/modelzoo/tencent:/models/tencent/1'
      - '/home/marvin/workspace/DeepRec/modelzoo/tencent/tf_logs_dir:/tmp/tensorboard'
  profiler:
    image: tensorboard_profiler:latest
    ports:
      - '6006:6006'
    volumes:
      - '/home/marvin/workspace/DeepRec/modelzoo/tencent/tf_logs_dir:/tmp/tensorboard'

