#test image
deeprec_test_image: cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:latest
tf_test_image: cesg-prc-registry.cn-beijing.cr.aliyuncs.com/cesg-ali/deeprec-modelzoo:tf

#test model default: [WDL, DLRM ,DeepFM, DSSM, DIEN, DIN]
test_model: 
  - DLRM
  - WDL
  - DeepFM
  - DSSM
  - DIEN
  - DIN
  
#batchsize map<model,batchsize>
model_batchsize:
  WDL: 512
  DLRM: 512
  DeepFM: 512
  DSSM: 4096
  DIEN: 512
  DIN: 512
  
#args for deeprec
modelArgs:

#tf on/off
stocktf: on


# env config 
env_var:
  - export START_STATISTIC_STEP=100
  - export STOP_STATISTIC_STEP=200
  - export TF_LAYOUT_PASS_GRAPH_ENABLE_ONLY_WHITE_LIST=1
  - export TF_LAYOUT_PASS_GRAPH_CAST_FUSION=1
  - export TF_LAYOUT_PASS_ONLY_WHITE_LIST=1
